### PR TITLE
update slack channel in docs and add missing gh actions

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to bb388d874bc88478e63690f8e090cbaa1dddadfe
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to ac06bab3aa10a35ab02a615c19ebcd02f05ee523
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to 7567d290bf78c0600138911b67ed2e3f5c96f086
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to d93baad639497a3844ba1767d1b25bb065f505fe
No significant bundle size differences found.

**Pull request merged**
