### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to 0619ec5089d697c9fc59322920b1a48b43ae116a
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to 030abbabb17840a16093a2dd60226526ab15ef73
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to e0163327d1fd0be934d56e7ecaa0744e49190469
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to e1ccad5f0a0218b821f88233b72256e3759e12ca
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-big-number bundle size difference from 2.0.0 to 77ab4d4f217824a093d17f0dfe39e328194a4fd2
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Pull request merged**
